src/Entity/Profil.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfilRepository")
 */
class Profil
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_nee;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $niveau;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $pays;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $ville;

    public function __construct()
    {
        $this->setType(0);
        $this->setNiveau(0);
    }
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", mappedBy="profil" )
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNee(): ?\DateTimeInterface
    {
        return $this->date_nee;
    }

    public function setDateNee(?\DateTimeInterface $date_nee): self
    {
        $this->date_nee = $date_nee;

        return $this;
    }

    public function getNiveau(): ?int
    {
        return $this->niveau;
    }

    public function setNiveau(?int $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ProfilType.php
<?php

namespace App\Form;

use App\Entity\Profil;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_nee', BirthdayType::class, [
                'placeholder' => [
                    'day' => 'Day', 'month' => 'Month', 'year' => 'Year',
                ],
                'format' => 'dd-MM-yyyy',
            ])
            ->add('adress')
            ->add('ville')
            ->add('pays')
            ->add('code_postal');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Profil::class,
        ]);
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Profil;
use App\Form\ProfilType;
use App\Repository\ProfilRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/profil")
 */
class ProfilController extends AbstractController
{
    /**
     * @Route("/", name="profil_index", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function index(ProfilRepository $profilRepository): Response
    {
        return $this->render('profil/index.html.twig', [
            'profils' => $profilRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="profil_new", methods={"GET","POST"})
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function new(Request $request): Response
    {
        $profil = new Profil();
        $form = $this->createForm(ProfilType::class, $profil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($profil);
            $entityManager->flush();

            return $this->redirectToRoute('profil_index');
        }

        return $this->render('profil/new.html.twig', [
            'profil' => $profil,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="profil_show", methods={"GET"})
     * @Security("is_granted('ROLE_USER')")
     */
    public function show(Profil $profil): Response
    {
        return $this->render('profil/show.html.twig', [
            'profil' => $profil,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="profil_edit", methods={"GET","POST"})
     * @Security("is_granted('ROLE_USER')")
     */
    public function edit(Request $request, Profil $profil): Response
    {
        $form = $this->createForm(ProfilType::class, $profil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profil_show', ['id' => $profil->getId()]);
        }

        return $this->render('profil/edit.html.twig', [
            'profil' => $profil,
            'form' => $form->createView(),
        ]);
    }

    /**
     * //@Route("/{id}", name="profil_delete", methods={"DELETE"})
     * //@Security("is_granted('ROLE_USER')")
     *
     * public function delete(Request $request, Profil $profil): Response
     * {
     *   if ($this->isCsrfTokenValid('delete' . $profil->getId(), $request->request->get('_token'))) {
     *       $entityManager = $this->getDoctrine()->getManager();
     *       $entityManager->remove($profil);
     *       $entityManager->flush();
     *   }
     *
     *     return $this->redirectToRoute('profil_index');
     * }
     */
}

templates/profil/_delete_form.html.twig
<form method="post" action="{{ path('profil_delete', {'id': profil.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ profil.id) }}">
    <button class="btn">Delete</button>
</form>

templates/profil/_form.html.twig
{{ form_start(form) }}
{% embed "decorators/_card.html.twig" %}
    {% block body %}
    {{ form_errors(form) }}
    <div class="form-group">
    {{ form_row(form.nom, { 'label': 'Nom' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.prenom, { 'label': 'Prenom' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.date_nee, { 'label': 'Date de naissance' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.adress, { 'label': 'Adresse' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.code_postal, { 'label': 'Code postal' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.ville, { 'label': 'Ville' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.pays, { 'label': 'Pays' }) }}
    </div>
    <div class="form-group">
    <button class="btn btn-dark {{btn_class}}">{{ button_label|default('Save') }}</button>
    </div>
    {% endblock %}
{% endembed %}
{{ form_end(form) }}

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profil{% endblock %}

{% block body %}
 {% embed "decorators/_card.html.twig" with {'class': ''} %}
    {% block header %}
        <h4>Edit profil</h4>
    {% endblock %}
    {% block body %}
{% if app.user.profil == profil %}
    {{ include('profil/_form.html.twig', {'button_label': ' ','btn_class': 'fas fa-save' }) }}
{% else %}
    <p>Vous ne pouvez pas modifier le profil d'un autre utilisateur.</p>
{% endif %}
    {% endblock %}
    {% endembed %}
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil index{% endblock %}

{% block body %}
    <h1>Profil index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_nee</th>
                <th>Niveau</th>
                <th>Type</th>
                <th>Adress</th>
                <th>Pays</th>
                <th>Code_postal</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for profil in profils %}
            <tr>
                <td>{{ profil.id }}</td>
                <td>{{ profil.nom }}</td>
                <td>{{ profil.prenom }}</td>
                <td>{{ profil.dateNee ? profil.dateNee|date('Y-m-d') : '' }}</td>
                <td>{{ profil.niveau }}</td>
                <td>{{ profil.type }}</td>
                <td>{{ profil.adress }}</td>
                <td>{{ profil.pays }}</td>
                <td>{{ profil.codePostal }}</td>
                <td>
                    <a href="{{ path('profil_show', {'id': profil.id}) }}"><i class="fas fa-eye fa-2x"></i></a>
                    <a href="{{ path('profil_edit', {'id': profil.id}) }}"><i class="fas fa-edit fa-2x"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('profil_new') }}"><i class="fas fa-plus-square fa-3x"></i></a>
{% endblock %}

templates/profil/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Profil{% endblock %}

{% block body %}
    <h1>Create new Profil</h1>

    {{ include('profil/_form.html.twig') }}

    <a href="{{ path('profil_index') }}">back to list</a>
{% endblock %}

templates/profil/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Fiche Profil{% endblock %}

{% block body %}
    <div class="row d-flex justify-content-center">
    <div class="col-10 col-md-6">
    {% embed "decorators/_card.html.twig" with {'class': 'm-1'} %}

    {% block header %}
    {% if app.user.profil == profil %}
    <h3><a href="{{ path('profil_show', {'id': profil.id}) }}">{{ profil.nom }} {{ profil.prenom }}</a></h3>
    {% endif %}
    {% endblock %}
    {% block body %}
    {% if app.user.profil == profil or is_granted('ROLE_ADMIN') %}
        <table class="table">
            <tbody>
                <tr>
                    <th>Date de naissance</th>
                    <td><i>{{ profil.dateNee|date('00/00/0000')}}</i></td>
                </tr>
                <tr>
                    <th>Adresse</th>
                    <td>{{ profil.adress }}</td>
                </tr>
                <tr>
                    <th>Code postal</th>
                    <td>{{ profil.codePostal }}</td>
                </tr>
                <tr>
                    <th>Ville</th>
                    <td>{{ profil.ville }}</td>
                </tr>
                <tr>
                    <th>Pays</th>
                    <td>{{ profil.pays }}</td>
                </tr>
                
                <tr>
                    <td>
                        <a class="btn" href="{{ path('profil_edit', {'id': profil.id}) }}"><i class="fas fa-edit fa-2x"></i></a>
                    </td>
                    <td></td>
                </tr>
                
            </tbody>
        </table>
    {% endif %}
    {% endblock %}
    {% endembed %}
    </div>
    {% include "badge/index.html.twig" with {"badges":profil.user.badges} %}
    </div>
{% endblock %}