src/Entity/TicketAgenda.php
<?php

namespace App\Entity;

use App\Repository\TicketAgendaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TicketAgendaRepository::class)
 */
class TicketAgenda
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_event;

    /**
     * @ORM\Column(type="text")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ticketAgendas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function __construct()
    {
        $this->date_create = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEvent(): ?\DateTimeInterface
    {
        return $this->date_event;
    }

    public function setDateEvent(\DateTimeInterface $date_event): self
    {
        $this->date_event = $date_event;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/TicketAgendaType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\TicketAgenda;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class TicketAgendaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_event')
            ->add('title')
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Tournoi' => 0,
                    'Festival' => 1,
                    'Stream' => 2,
                    'Autres' => 3,
                ],
            ])
            ->add('description');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TicketAgenda::class,
        ]);
    }
}

src/Controller/TicketAgendaController.php
<?php

namespace App\Controller;

use App\Entity\TicketAgenda;
use App\Form\TicketAgendaType;
use App\Repository\TicketAgendaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/ticket/agenda")
 */
class TicketAgendaController extends AbstractController
{
    /**
     * @Route("/", name="ticket_agenda_index", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_USER')")
     */
    public function index(TicketAgendaRepository $ticketAgendaRepository): Response
    {
        return $this->render('ticket_agenda/index.html.twig', [
            'ticket_agendas' => $ticketAgendaRepository->findByUser($this->getUser()),
        ]);
    }

    /**
     * @Route("/new", name="ticket_agenda_new", methods={"GET","POST"})
     * @Security("is_granted('ROLE_USER')")
     */
    public function new(Request $request): Response
    {
        $ticketAgenda = new TicketAgenda();
        $ticketAgenda->setUser($this->getUser());
        $form = $this->createForm(TicketAgendaType::class, $ticketAgenda);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ticketAgenda);
            $entityManager->flush();

            return $this->redirectToRoute('ticket_agenda_index');
        }

        return $this->render('ticket_agenda/new.html.twig', [
            'ticket_agenda' => $ticketAgenda,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticket_agenda_show", methods={"GET"})
     * @Security("is_granted('ROLE_USER')")
     */
    public function show(TicketAgenda $ticketAgenda): Response
    {
        return $this->render('ticket_agenda/show.html.twig', [
            'ticket_agenda' => $ticketAgenda,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ticket_agenda_edit", methods={"GET","POST"})
     * @Security("is_granted('ROLE_USER')")
     */
    public function edit(Request $request, TicketAgenda $ticketAgenda): Response
    {
        $form = $this->createForm(TicketAgendaType::class, $ticketAgenda);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ticket_agenda_index');
        }

        return $this->render('ticket_agenda/edit.html.twig', [
            'ticket_agenda' => $ticketAgenda,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticket_agenda_delete", methods={"DELETE"})
     * @Security("is_granted('ROLE_USER')")
     */
    public function delete(Request $request, TicketAgenda $ticketAgenda): Response
    {
        if ($this->isCsrfTokenValid('delete' . $ticketAgenda->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ticketAgenda);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ticket_agenda_index');
    }
}

templates/ticket_agenda/_delete_form.html.twig
<form method="post" action="{{ path('ticket_agenda_delete', {'id': ticket_agenda.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket_agenda.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ticket_agenda/_form.html.twig
{{ form_start(form) }}
{% embed "decorators/_card.html.twig" %}
    {% block body %}
    {{ form_errors(form) }}
    <div class="form-group">
    {{ form_row(form.title, { 'label': 'Titre' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.date_event, { 'label': 'Date de l\'événement' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.type, { 'label': 'Type de l\'événement' }) }}
    </div>
    <div class="form-group">
    {{ form_row(form.description, { 'label': 'Description' }) }}
    </div>
    <div class="form-group">
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    </div>
    {% endblock %}
{% endembed %}
{{ form_end(form) }}

templates/ticket_agenda/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TicketAgenda{% endblock %}

{% block body %}
    <h1>Edit TicketAgenda</h1>

    {{ include('ticket_agenda/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('ticket_agenda_index') }}">back to list</a>

    {{ include('ticket_agenda/_delete_form.html.twig') }}
{% endblock %}

templates/ticket_agenda/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agenda{% endblock %}

{% block body %}
    <h1>Votre Agenda</h1>
    
    {{ include ('decorators/_calendar.html.twig') }}
    
    <h2 class="mx-3">Votre liste d'événements</h2>
    <table class="table table-sm text-center">
        <thead>
            <tr class="bg-info">
                {% if is_granted('ROLE_ADMIN') %}
                <th>Id</th>
                {% endif %}
                <th>Titre</th>
                <th>Date de l'event</th>
                <th>Description</th>
                <th>Type</th>
                <th>Date de création</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ticket_agenda in ticket_agendas %}
            <tr>
                {% if is_granted('ROLE_ADMIN') %}
                <td>{{ ticket_agenda.id }}</td>
                {% endif %}
                <td>{{ ticket_agenda.title }}</td>
                <td>{{ ticket_agenda.dateEvent ? ticket_agenda.dateEvent|date('d-m-Y H:i:s') : '' }}</td>
                <td>{{ ticket_agenda.description }}</td>
                <td id="ticketType">{{ ticket_agenda.type }}</td>
                <td>{{ ticket_agenda.dateCreate ? ticket_agenda.dateCreate|date('d-m-Y') : '' }}</td>
                <td>
                    <a id="btnShow" href="{{ path('ticket_agenda_show', {'id': ticket_agenda.id}) }}"><i class="fas fa-eye fa-2x"></i></a>
                    <a id="btnEdit" href="{{ path('ticket_agenda_edit', {'id': ticket_agenda.id}) }}"><i class="fas fa-edit fa-2x"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a id="btnNew"class="mx-5 d-flex flex-row-reverse" href="{{ path('ticket_agenda_new') }}"><i class="fas fa-plus-square fa-3x"></i></a>
{% endblock %}

templates/ticket_agenda/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1>Votre nouvel événement</h1>

    {{ include('ticket_agenda/_form.html.twig') }}

    <a href="{{ path('ticket_agenda_index') }}"><i class="return" class="fas fa-arrow-alt-circle-left fa-2x"></i>Retourner à mon Agenda</a>
{% endblock %}

templates/ticket_agenda/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TicketAgenda{% endblock %}

{% block body %}

    <h1>TicketAgenda</h1>

    <table class="table">
        <tbody>
            <tr>
                <th class="bg-info">Titre</th>
                <td>{{ ticket_agenda.title }}</td>
            </tr>
            <tr>
                <th class="bg-info">Date de l'événement</th>
                <td>{{ ticket_agenda.dateEvent ? ticket_agenda.dateEvent|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th class="bg-info">Type</th>
                <td class="ticketType">{{ ticket_agenda.type }}</td>
            </tr>
            <tr>
                <th class="bg-info">Description</th>
                <td>{{ ticket_agenda.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ticket_agenda_index') }}">back to list</a>

    <a href="{{ path('ticket_agenda_edit', {'id': ticket_agenda.id}) }}">edit</a>

    {{ include('ticket_agenda/_delete_form.html.twig') }}
{% endblock %}